version: "3.8"

services:
    db:
        image: mysql:8.0
        container_name: mysql_container
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ankadb
            MYSQL_USER: allan
            MYSQL_PASSWORD: senha123
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql

volumes:
    mysql_data:
